### PR TITLE
Fix link to ranking tutorial

### PR DESCRIPTION
**Pull request by wingrime**
Fix link to ranking tutorials

They are in separate repo now

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en.

### CODE REVIEW

**Comment by annaveronika** [comment]
@arcadia-devtools Ship it!

**Comment by annaveronika** [comment]
You need to agree to the terms of the CLA, see examples in incoming pr-s in catboost repo.

**Comment by wingrime** [comment]
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en.

**Comment by annaveronika** [comment]
@arcadia-devtools Ship it!

**Comment by wingrime** [comment]
still open?

**Comment by annaveronika** [comment]
@arcadia-devtools Ship it!

**Comment by annaveronika** [comment]
@wingrime Very sorry for the delay! We had automatic sync to our main repo only for catboost/catboost. We are adding it now for other repos, it'll be merged soon.

**Comment by arcadia-devtools** [comment]
@annaveronika, internal review request created: 668691

**Comment by annaveronika** [comment]
@wingrime It's finally merged! Thanks a lot!

**Pull request merged**
